language: python
python:
    - "3.4"
    - "nightly"
install:
    - "pip install ."
script:
    - "python -m unittest discover"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7498c1d7f0e50c212e1a
