language: python

python:
    - "3.4"
    - "3.5"
    - "nightly"

install:
    - "pip install python-coveralls"
    - "pip install ."

script:
    - python setup.py test

after_success:
    - coveralls

notifications:
    webhooks:
        urls:
            - https://webhooks.gitter.im/e/7498c1d7f0e50c212e1a

matrix:
    allow_failures:
        - python: "nightly"
