language: python

python:
    - "3.4"
    - "3.5"
    - "3.5.1"
    - "nightly"

install:
    - "pip install -U pip"
    - "pip install -U pytest python-coveralls"
    - "pip install ."
    - "pip freeze"

script:
    - python setup.py test

after_success:
    - coveralls

notifications:
    webhooks:
        urls:
            - https://webhooks.gitter.im/e/7498c1d7f0e50c212e1a

matrix:
    allow_failures:
        - python: "nightly"
        - python: "3.5"  # maybe there is a bug of sqlite3 in 3.5.0
