language: python

jobs:
    fast_finish: true
    allow_failures:
        - python: "nightly"
    include:
        - stage: test
          os: linux
          python: 3.4
        - stage: test
          os: linux
          python: 3.5
        - stage: test
          os: linux
          python: 3.6
        - stage: test
          os: linux
          python: "nightly"
        # Python runtime is not yet available on OS X
        # https://github.com/travis-ci/travis-ci/issues/2312
        - stage: test
          os: osx
          language: generic
          env: PYTHON_VERSION=3.4.8
        - stage: test
          os: osx
          language: generic
          env: PYTHON_VERSION=3.5.5
        - stage: test
          os: osx
          language: generic
          env: PYTHON_VERSION=3.6.4

        - stage: deploy
          os: linux
          python: 3.4
          script: skip
          deploy: &pypi
            provider: pypi
            user: M157q
            password:
                secure: SxXAmsEixEw9bIiSTFiRxU4JiILsLZ/wMRys+w5zwmHftyI6+div5j1FcwtxsmAGcSSzsNgKvF9OBCcKuaJ6rlHf87pf13CxsCeZubKKHod7aMywjTtSKRGA70fKB5h+p0qomRgpV1njvgPwLcLeEbr9rHTxjIXBiE77P4E59zk=
            distributions: "sdist bdist_wheel"
            on:
                branch: master
                tags: true
                condition: $TRAVIS_EVENT_TYPE != cron

before_install:
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sh ci/install_python_for_osx.sh; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then source ~/venv/bin/activate; fi

install:
    - "pip install -U setuptools"   # for upgrade issue with setuptools and CPython 3.6 on Travis CI
    - "pip install -U pip"
    - "pip install -U pytest coveralls"
    - "pip install ."
    - "pip freeze"

script:
    - python setup.py test

after_success:
    - coveralls

notifications:
    webhooks:
        urls:
            - https://webhooks.gitter.im/e/7498c1d7f0e50c212e1a
